package exporters

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/KatrielMoses/PhoneAccess/internal/core"
	"github.com/KatrielMoses/PhoneAccess/internal/correlator"
	"github.com/jung-kurt/gofpdf"
)

type PDFExporter struct{}

func (PDFExporter) Format() string {
	return "pdf"
}

func (PDFExporter) Export(report *core.InvestigationReport, w io.Writer) error {
	if report == nil {
		return errors.New("export pdf: report is nil")
	}
	if w == nil {
		return errors.New("export pdf: writer is nil")
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetTitle("PhoneAccess Investigation Report", false)
	pdf.SetAuthor("PhoneAccess", false)
	pdf.SetMargins(16, 18, 16)
	pdf.SetAutoPageBreak(true, 22)
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(100, 100, 100)
		pdf.CellFormat(0, 4, "Generated by PhoneAccess - for lawful security research only", "", 1, "C", false, 0, "")
		pdf.CellFormat(0, 4, fmt.Sprintf("Page %d", pdf.PageNo()), "", 0, "C", false, 0, "")
	})

	pdf.AddPage()
	writeCover(pdf, report)
	writeSection(pdf, "NUMBER INTELLIGENCE", numberPairs(report), nil)
	writeModuleSection(pdf, report, "carrier", "CARRIER INTELLIGENCE", []string{
		"carrier", "carrier_confidence", "line_type", "line_type_confidence", "voip_suspected", "voip_provider", "timezone", "data_source",
	}, nil)
	writeModuleSection(pdf, report, "spam", "SPAM & REPUTATION", []string{
		"risk", "spam_score", "total_reports", "sources_with_hits", "caller_type", "most_recent_report",
	}, []string{"report_snippets"})
	writeModuleSection(pdf, report, "breach", "BREACH INTELLIGENCE", []string{
		"found", "breach_count", "stealer_count", "compromised_machines", "credentials_found", "most_recent_breach", "data_classes_seen",
	}, []string{"breaches"})
	writeModuleSection(pdf, report, "reverse", "REVERSE LOOKUP", []string{
		"name_hint", "name_confidence", "location_hint", "sources_with_hits", "sources_checked", "pivot_emails", "pivot_usernames",
	}, []string{"raw_hits"})
	writeMessengerPresence(pdf, report)
	writeIdentityGraph(pdf, report)
	writeIdentityRecord(pdf, report)
	writeModuleSection(pdf, report, "enumerator", "SERVICE ENUMERATION", []string{
		"found", "hit_count", "checked", "total_services", "categories_hit", "category_breakdown", "discovered_names", "discovered_usernames", "source_statuses",
	}, []string{"hits"})
	writeModuleSection(pdf, report, "voip", "VOIP INTELLIGENCE", []string{
		"is_voip", "confidence", "provider", "is_prepaid", "data_source", "line_type", "carrier", "country",
	}, []string{"risk_signals"})
	writeModuleSection(pdf, report, "geo", "GEOGRAPHIC INTELLIGENCE", []string{
		"area_code_origin", "area_code_split_history", "likely_ported", "ported_reason", "local_time", "utc_offset", "business_hours", "regional_risk_flag", "regional_risk_region",
	}, []string{"regional_risk_basis"})

	if err := pdf.Error(); err != nil {
		return fmt.Errorf("render pdf: %w", err)
	}
	if err := pdf.Output(w); err != nil {
		return fmt.Errorf("write pdf: %w", err)
	}
	return nil
}

func writeMessengerPresence(pdf *gofpdf.Fpdf, report *core.InvestigationReport) {
	writeModuleSection(pdf, report, "telegram", "MESSENGER PRESENCE - TELEGRAM", []string{
		"found", "display_name", "username", "bio", "last_seen_bucket", "account_id", "profile_photo_path", "profile_photo_phash", "data_source",
	}, nil)
	addProfileImage(pdf, moduleFinding(report, "telegram", "profile_photo_path"))
	writeModuleSection(pdf, report, "whatsapp", "MESSENGER PRESENCE - WHATSAPP", []string{
		"found", "display_name", "about_bio", "profile_photo_path", "profile_photo_phash", "data_source",
	}, nil)
	addProfileImage(pdf, moduleFinding(report, "whatsapp", "profile_photo_path"))
}

func addProfileImage(pdf *gofpdf.Fpdf, path string) {
	path = strings.TrimSpace(path)
	if path == "" {
		return
	}
	opt := gofpdf.ImageOptions{ReadDpi: true}
	y := pdf.GetY()
	pdf.ImageOptions(path, 16, y+2, 28, 28, false, opt, 0, "")
	pdf.SetY(y + 32)
}

func writeCover(pdf *gofpdf.Fpdf, report *core.InvestigationReport) {
	phone := ""
	if report.Number != nil {
		phone = firstNonEmpty(report.Number.E164, report.Number.RawInput)
	}
	risk := reportRiskScore(report)

	pdf.SetTextColor(25, 66, 112)
	pdf.SetFont("Helvetica", "B", 28)
	pdf.CellFormat(0, 12, "PhoneAccess", "", 1, "L", false, 0, "")
	pdf.SetTextColor(35, 35, 35)
	pdf.SetFont("Helvetica", "B", 20)
	pdf.CellFormat(0, 10, "Investigation Report", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)
	pdf.CellFormat(0, 7, "Phone number: "+empty(phone), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 7, "Generated: "+report.GeneratedAt.UTC().Format("2006-01-02 15:04:05 UTC"), "", 1, "L", false, 0, "")
	pdf.Ln(6)

	pdf.SetFillColor(242, 246, 250)
	pdf.SetDrawColor(180, 195, 210)
	pdf.RoundedRect(16, pdf.GetY(), 178, 24, 2, "1234", "DF")
	pdf.SetXY(21, pdf.GetY()+4)
	pdf.SetFont("Helvetica", "B", 13)
	pdf.SetTextColor(40, 40, 40)
	pdf.CellFormat(60, 7, "Overall Risk", "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 18)
	pdf.CellFormat(35, 7, fmt.Sprintf("%d/100", risk.Score), "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 13)
	pdf.CellFormat(60, 7, string(risk.Band), "", 1, "L", false, 0, "")
	pdf.SetXY(21, pdf.GetY()+1)
	pdf.SetFont("Helvetica", "", 9)
	pdf.MultiCell(168, 5, risk.Summary, "", "L", false)
	if len(risk.Drivers) > 0 {
		pdf.SetX(21)
		pdf.MultiCell(168, 5, "Drivers: "+formatRiskDrivers(risk.Drivers), "", "L", false)
	}
	pdf.Ln(7)
}

func writeSection(pdf *gofpdf.Fpdf, title string, pairs [][2]string, body []string) {
	pdf.Ln(2)
	pdf.SetFillColor(25, 66, 112)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(0, 7, title, "", 1, "L", true, 0, "")
	pdf.SetTextColor(35, 35, 35)
	pdf.SetFont("Helvetica", "", 9)
	for _, pair := range pairs {
		if strings.TrimSpace(pair[1]) == "" {
			continue
		}
		pdf.SetFont("Helvetica", "B", 9)
		pdf.CellFormat(44, 6, humanize(pair[0]), "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 9)
		pdf.MultiCell(0, 6, pair[1], "", "L", false)
	}
	if len(body) > 0 {
		pdf.Ln(1)
		pdf.SetLeftMargin(22)
		for _, line := range body {
			pdf.MultiCell(0, 5, line, "", "L", false)
		}
		pdf.SetLeftMargin(16)
	}
}

func writeModuleSection(pdf *gofpdf.Fpdf, report *core.InvestigationReport, moduleName, title string, preferred, bodyKeys []string) {
	result := moduleResult(report, moduleName)
	if result == nil {
		writeSection(pdf, title, [][2]string{{"status", "not available"}}, nil)
		return
	}

	pairs := [][2]string{{"status", string(result.Status)}}
	seen := map[string]bool{}
	for _, key := range preferred {
		seen[key] = true
		if result.Findings != nil {
			pairs = append(pairs, [2]string{key, result.Findings[key]})
		}
	}
	keys := make([]string, 0, len(result.Findings))
	for key := range result.Findings {
		if !seen[key] && !contains(bodyKeys, key) {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	for _, key := range keys {
		pairs = append(pairs, [2]string{key, result.Findings[key]})
	}

	body := []string{}
	for _, key := range bodyKeys {
		body = append(body, splitMulti(result.Findings[key])...)
	}
	for _, evidence := range result.Evidence {
		if strings.TrimSpace(evidence) != "" {
			body = append(body, "Evidence: "+strings.TrimSpace(evidence))
		}
	}
	writeSection(pdf, title, pairs, body)
}

func moduleFinding(report *core.InvestigationReport, moduleName, key string) string {
	result := moduleResult(report, moduleName)
	if result == nil || result.Findings == nil {
		return ""
	}
	return result.Findings[key]
}

func writeIdentityGraph(pdf *gofpdf.Fpdf, report *core.InvestigationReport) {
	title := "IDENTITY GRAPH"
	if report.IdentityGraph == nil || len(report.IdentityGraph.PivotPoints) == 0 {
		writeSection(pdf, title, [][2]string{{"pivots", "none discovered"}}, nil)
		return
	}

	pdf.Ln(2)
	pdf.SetFillColor(25, 66, 112)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(0, 7, title, "", 1, "L", true, 0, "")
	y := pdf.GetY()
	pdf.SetFillColor(248, 249, 242)
	pdf.SetDrawColor(205, 205, 180)
	pdf.RoundedRect(16, y+1, 178, 8+float64(len(report.IdentityGraph.PivotPoints)+len(report.IdentityGraph.SuggestedCommands))*5, 2, "1234", "DF")
	pdf.SetXY(21, y+5)
	pdf.SetTextColor(35, 35, 35)
	pdf.SetFont("Helvetica", "", 9)
	for _, pivot := range report.IdentityGraph.PivotPoints {
		line := fmt.Sprintf("%s: %s (%s via %s)", pivot.Type, pivot.Value, pivot.Confidence, strings.Join(pivot.Modules, ", "))
		pdf.MultiCell(168, 5, line, "", "L", false)
	}
	if len(report.IdentityGraph.SuggestedCommands) > 0 {
		pdf.Ln(1)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.CellFormat(168, 5, "Suggested follow-up commands", "", 1, "L", false, 0, "")
		pdf.SetFont("Courier", "", 8)
		for _, command := range report.IdentityGraph.SuggestedCommands {
			pdf.MultiCell(168, 5, command, "", "L", false)
		}
	}
	pdf.SetXY(16, pdf.GetY()+4)
}

func writeIdentityRecord(pdf *gofpdf.Fpdf, report *core.InvestigationReport) {
	record := exportIdentityRecord(report)
	if record == nil {
		writeSection(pdf, "IDENTITY RECORD", [][2]string{{"status", "not available"}}, nil)
		return
	}

	pairs := [][2]string{
		{"status", record.Status},
		{"jurisdiction", record.Jurisdiction},
		{"overall_confidence", fmt.Sprintf("%.2f", record.OverallConfidence)},
	}
	if record.Status == correlator.StatusSkipped {
		pairs = append(pairs, [2]string{"note", record.Note})
		writeSection(pdf, "IDENTITY RECORD", pairs, nil)
		return
	}
	if top := exportTopVisible(record.Names); top != nil {
		pairs = append(pairs, [2]string{"top_name", exportCandidateLine(*top)})
	} else {
		pairs = append(pairs, [2]string{"top_name", "none above display threshold"})
	}
	if top := exportTopVisible(record.Addresses); top != nil {
		pairs = append(pairs, [2]string{"top_address", exportCandidateLine(*top)})
	}
	if top := exportTopVisible(record.DOBs); top != nil {
		pairs = append(pairs, [2]string{"dob", exportCandidateLine(*top)})
	}
	if emails := exportVisibleValues(record.Emails, 5); len(emails) > 0 {
		pairs = append(pairs, [2]string{"email_pivots", strings.Join(emails, ", ")})
	}
	if record.SuppressedCount > 0 {
		pairs = append(pairs, [2]string{"suppressed", fmt.Sprintf("%d below 0.45 confidence; retained in JSON", record.SuppressedCount)})
	}

	body := []string{}
	for _, conflict := range record.Conflicts {
		body = append(body, fmt.Sprintf("Conflict %s: %s [%s] vs %s [%s], penalty %.2f",
			conflict.Field, conflict.ValueA, conflict.SourceA, conflict.ValueB, conflict.SourceB, conflict.PenaltyApplied))
	}
	for _, run := range record.SourceRuns {
		line := fmt.Sprintf("Source: %s - %s (%d claims)", run.Name, run.Status, run.ClaimsCount)
		if strings.TrimSpace(run.Error) != "" {
			line += ": " + run.Error
		}
		body = append(body, line)
	}
	writeSection(pdf, "IDENTITY RECORD", pairs, body)
}

func exportIdentityRecord(report *core.InvestigationReport) *correlator.UnifiedIdentityRecord {
	if report == nil || report.IdentityRecord == nil {
		return nil
	}
	if record, ok := report.IdentityRecord.(*correlator.UnifiedIdentityRecord); ok {
		return record
	}
	data, err := json.Marshal(report.IdentityRecord)
	if err != nil {
		return nil
	}
	var record correlator.UnifiedIdentityRecord
	if err := json.Unmarshal(data, &record); err != nil {
		return nil
	}
	return &record
}

func exportTopVisible(candidates []correlator.FieldCandidate) *correlator.FieldCandidate {
	for i := range candidates {
		if !candidates[i].Suppressed && candidates[i].Confidence >= correlator.LowConfidenceThreshold {
			return &candidates[i]
		}
	}
	return nil
}

func exportVisibleValues(candidates []correlator.FieldCandidate, limit int) []string {
	values := []string{}
	for _, candidate := range candidates {
		if candidate.Suppressed || candidate.Confidence < correlator.LowConfidenceThreshold {
			continue
		}
		values = append(values, candidate.DisplayValue)
		if len(values) == limit {
			break
		}
	}
	return values
}

func exportCandidateLine(candidate correlator.FieldCandidate) string {
	sources := make([]string, 0, len(candidate.Sources))
	for _, source := range candidate.Sources {
		if source.Name != "" {
			sources = append(sources, source.Name)
		}
	}
	if len(sources) == 0 {
		sources = append(sources, "unknown source")
	}
	return fmt.Sprintf("%s (%s, %.2f via %s)", candidate.DisplayValue, candidate.ConfidenceLabel, candidate.Confidence, strings.Join(sources, ", "))
}

func numberPairs(report *core.InvestigationReport) [][2]string {
	if report.Number == nil {
		return [][2]string{{"status", "not available"}}
	}
	number := report.Number
	return [][2]string{
		{"raw_input", number.RawInput},
		{"normalized", number.E164},
		{"valid", fmt.Sprintf("%t", number.Valid)},
		{"country", fmt.Sprintf("+%d (%s)", number.CountryCode, number.CountryAlpha2)},
		{"national_number", number.NationalNumber},
		{"region", number.RegionDescription},
		{"line_type", string(number.LineType)},
		{"carrier_hint", number.CarrierHint},
		{"timezone", number.Timezone},
	}
}

func humanize(key string) string {
	key = strings.ReplaceAll(key, "_", " ")
	if key == "" {
		return key
	}
	return strings.ToUpper(key[:1]) + key[1:]
}

func empty(value string) string {
	if strings.TrimSpace(value) == "" {
		return "unknown"
	}
	return value
}

func contains(values []string, needle string) bool {
	for _, value := range values {
		if value == needle {
			return true
		}
	}
	return false
}
